name: Testing purpose
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment to perform: (develop, stage, preprod, prod)'
        required: true
        default: 'develop'

jobs:
  build:
    name: Sending message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Test
        run: .github/scripts/hello.sh
