name: Testing purpose
on:
  workflow_dispatch:
    inputs:
      chromium-version:
          description: What is the Chromium version to upload?
          required: true
          default: 112.0.0
          type: string
jobs:
  build:
    name: "Chromium version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Test
        run: |
          echo "The chromium version to upload is: ${{ github.event.inputs.chromium-version }}"
