name: Testing purpose
on:
  workflow_dispatch:
    inputs:
      chromium-version:
          description: What is the chromium version to upload?
          required: true
          default: 114.0.0
          type: string
      environment:
        type: environment
jobs:
  build:
    name: "Sending message [chromium-version: ${{ github.event.inputs.chromium-version }}]"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Test
        run: |
          echo "Var1: ${{ github.event.inputs.chromium-version }}"
